Network/DNS/Decode.hs, Network/DNS/StateBinary.hs
Resolves #33 
- Add `runSGetWithLeftovers` to return leftovers after decoding using `SGet`
- Add `decodeMany` to parse many length-encoded DNS records (e.g. from TCP traffic)
=> Support leftovers, add decodeMany function

Network/DNS/Decode.hs, Network/DNS/Internal.hs, dns.cabal
`toEnum` will fail with an error call if the value is not in bounds. For some DNS messages, this causes the parser to fail.
=> Use Safe.toEnumMay to handle unsupported opcodes gracefully

Network/DNS/Resolver.hs
The preprocessor I use defines `unix=1` and I believe there's no harm in renaming it.
=> Rename a variable to fix preprocessor conflicts

test2/doctests.hs
Before the change tests fail on system
with many packages including iproute
and network-data installed globally:
Test suite logged to: dist/test/dns-2.0.5-spec.log
Test suite doctest: RUNNING...
Network/DNS/Decode.hs:20:1: error:
Ambiguous interface for ‘Data.IP’:
it was found in multiple packages: network-data-0.5.3 iproute-1.7.0
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
=> test2/doctests.hs: ignore 'network-data' package

Network/DNS/Internal.hs
It is sometimes useful to sort RRs in a predictable order.  It would also be useful to be able to sort RData objects in their canonical wire form, because signatures on DNSSEC records are over such sorted representations of RRsets, but that is for another time...
=> Make it possible to sort more DNS data types

Network/DNS/Decode.hs
We would like this change made to stop an exception from occurring-- specifically `toIPv4` from iproute calls `error` when not given exactly 4 `Int`s, similarly for `toIPv6b`.
=> Length checks

Network/DNS/Decode.hs, Network/DNS/Encode.hs
Without this, records like:
arlott.org.uk. IN MX 0 .
fail to display correctly (the final "." is missing), and conversely
lookups of the various (e.g. NS) records of the root domain "." fail.
=> Better handling of encoding and decoding the "root" domain "."

Network/DNS/Decode.hs, Network/DNS/Encode.hs, Network/DNS/Internal.hs, Network/DNS/Lookup.hs, Network/DNS/Resolver.hs
For example, the TLSA records for ``_25._tcp.mail.socialmiwu.de`` don't fit in a 512-byte UDP response (dig reports 596 bytes, and fails over to TCP, when EDNS0 is disabled).  The updated code is likewise able to retrieve the answer over TCP.
Please check that the implementation style matches how you want to code to be structured.  This PR strays into new territory for me, and it is less obvious what the preferred method is for reading the length bytes from a TCP socket, followed by that many bytes of response.
I should also note, that it is not clear how ParseErrors should be reported.  Should these be turned into (new?) DNS errors, or remain exceptions for the caller to `catch` (unlike DNS errors that are returned via ``Either``).  Mind you, this question is certainly not new with the …
=> Implemented TCP fallback after a truncated UDP response.

Network/DNS/Decode.hs, Network/DNS/Encode.hs, Network/DNS/Internal.hs, Network/DNS/Resolver.hs
Though the pattern guard was legitimate, it was unnecessary, so I simplified it anyway.
While I was there, I took the opportunity to split off local helper functions as top-level definitions, and add comments.  This work adds no functionality and fixes no bugs, so does not merit a new release, but may be useful to stage for the next convenient opportunity.
Feedback welcome, this is supposed to make the code more clear.
Some of the comments ask questions about error handling, feedback on that especially welcome.
=> TCP retry code cleanup

Network/DNS/StateBinary.hs, test/RoundTripSpec.hs
Found when round-tripping packets captured with Wireshark.
=> Fix the StateBinary.get32 parser

Network/DNS/Decode.hs, Network/DNS/Encode.hs, Network/DNS/Internal.hs, Network/DNS/Resolver.hs, Network/DNS/StateBinary.hs, test/DecodeSpec.hs
DNS packets are small and there is little to no advantage of using
lazy ByteStrings.
=> Switch to strict ByteString

dns.cabal
It was removed in b00335f8b0a6e1c287f87450190fda266968ae58.
Or at the very least, according to its docs, it's merged into GHC 7.8, and since the Travis build here dropped 7.6, I'd guess it shouldn't be necessary.
=> Remove bytestring-builder dependency.

Network/DNS/Resolver.hs
Trying to build `dns` on GHC 8.2.1 on Windows yields this build error.
```
Building library for dns-2.0.10..
[1 of 9] Compiling Network.DNS.Internal ( Network\DNS\Internal.hs, dist\build\Network\DNS\Internal.o )
[2 of 9] Compiling Network.DNS.Types ( Network\DNS\Types.hs, dist\build\Network\DNS\Types.o )
[3 of 9] Compiling Network.DNS.StateBinary ( Network\DNS\StateBinary.hs, dist\build\Network\DNS\StateBinary.o )
[4 of 9] Compiling Network.DNS.Encode ( Network\DNS\Encode.hs, dist\build\Network\DNS\Encode.o )
[5 of 9] Compiling Network.DNS.Decode ( Network\DNS\Decode.hs, dist\build\Network\DNS\Decode.o )
[6 of 9] Compiling Network.DNS.Resolver ( Network\DNS\Resolver.hs, dist\build\Network\DNS\Resolver.o )
Network\DNS\Resolver.hs:446:21: error:
parse error on input `='
Perhaps you need a …
```
=> Fix Windows build

Network/DNS/Resolver.hs, Network/DNS/Types.hs, dns.cabal
Hey @kazu-yamamoto !
Incidentally this also fixes #28.
I've bite the bullet and I have opened the PR. My colleague @kantp confirms this patch effectively fixes his problems.
The gist of this patch:
* A `ResolvSeed` has been extended with a `NonEmpty AddrInfo`. Why `NonEmpty`? Because the contract here is that we need to ensure _at least_ one `AddrInfo` is in scope, and using a simple list won't capture it. `NonEmpty` is not exposed to user's code, it's only for internal safety.
* I have removed the `connectSocket` function, because it was too much of a degree of freedom. Now given a `ResolvSeed` you get back a `NonEmpty Socket` where all the sockets inside are correctly opened and connected.
* A `Resolver` keeps internally a `NonEmpty Socket`, one for each nameserver, which can be tried …
=> Fixed #80 (support multiple nameservers)

Network/DNS/Resolver.hs
When IO errors happen, it is useful to know where.  We annotate any
I/O exceptions with the protocol, address and port
=> Catch and annotate IO Exceptions in performLookup

Network/DNS/LookupRaw.hs, Network/DNS/Resolver.hs, Network/DNS/Types/Internal.hs
I don't think there should be a minimum TTL.  If we get a TTL less than 60s, we should either honour it or not cache the data, but we should not raise the received TTL.  My preference is to honour whatever TTL we get.
=> Remove minttl and cosmetic fixes

Network/DNS/Decode.hs, Network/DNS/Decode/Internal.hs, Network/DNS/IO.hs, Network/DNS/StateBinary.hs, Network/DNS/Types.hs, dns.cabal, test/DecodeSpec.hs, test2/IOSpec.hs
I hope this PR fixes #103 and #107.
- The decoder now holds the original input and can parse domains even if the structure of the target record is unknown. See #103 for more information. Note that I have not implemented `RRSIG`.
- The decoder now throws `DNSError` to fix #107. I'm sorry but it appeared that the `RD_PARSERR` approach is very difficult.
@benclifford and @vdukhovni Would you review this PR?
=> Improving decoder

Network/DNS/Decode/Internal.hs, Network/DNS/Encode.hs, Network/DNS/Types.hs, test/RoundTripSpec.hs
No further changes are required to support these extensions since they reuse the DNS message format.
=> Add NOTIFY and UPDATE opcodes

Network/DNS/Decode/Internal.hs, Network/DNS/Encode.hs, Network/DNS/IO.hs, Network/DNS/LookupRaw.hs, Network/DNS/Resolver.hs, Network/DNS/Transport.hs, Network/DNS/Types.hs, Network/DNS/Types/Internal.hs, test/EncodeSpec.hs, test/RoundTripSpec.hs, test2/IOSpec.hs
This can be done at the resolver level by setting default values for
new ResolvConf fields.  This makes it possible to request unvalidated
data from validating DNSSEC resolvers (by setting the CD bit) or
to query authoritative servers (by clearing the RD bit, since many
authoritative servers will refuse queries with the RD bit set, even
when authoritative for the query domain).
Alternatively, the new "lookupRaw'" function takes a "QueryFlags"
parameter which is a "newtype" around DNFlags with a hidden
constructor.  The "mkQueryFlags" function returns a "QueryFlags"
record in which only query-related flags can be modified.  The
"fromQueryFlags" accessor gives us back the contructed "DNSFlags".
With these changes one can configure per-resolver defaults for the
RD/AD/CD bits, or else choose …
=> Make use of the RD and CD bits configurable

Changelog.md, Network/DNS.hs, Network/DNS/Decode/Internal.hs, Network/DNS/Encode.hs, Network/DNS/IO.hs, Network/DNS/LookupRaw.hs, Network/DNS/Memo.hs, Network/DNS/Resolver.hs, Network/DNS/Transport.hs, Network/DNS/Types.hs, Network/DNS/Types/Internal.hs, test/EncodeSpec.hs, test/RoundTripSpec.hs, test2/IOSpec.hs
The five commits in this pull request change a lot of code.  Each builds on the previous one, and the code should build and test after each step (1, 1 + 2, 1 + 2 + 3, ...).
It may be easier to review the commits one at a time, and see fewer changes at a given time, with better focus on a particular set of issues.
On the other hand the combined set of patches change some pieces of code multiple times.  So it is perhaps more "effiecient" to review everything at once, if it is not too much to take in.
If you'd prefer a series of 5 pull requests, we could start with commit 1, get that done, then review 2, ...
My advice is to clone the branch, and review on your own machine with "git diff -U20" (or however much context you prefer), and then go to github only to make comments on anything you …
=> Edns overhaul

Network/DNS/Types.hs
Pattern synonyms can be exported without the "pattern" keyword from GHC 8.0.1
https://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/glasgow_exts.html#patsyn-impexp
=> Using Pattern synonyms in GHC 8.0.

Network/DNS/LookupRaw.hs, Network/DNS/Transport.hs, Network/DNS/Types.hs
@vdukhovni I have implemented some of your suggested changes from #134 in this new PR:
- documented CAA, including mention of the RFC
- added AXFR types
- added an error constructor to prevent sending an AXFR request from the existing interface
- added an error constructor to differentiate between sequence number and question mismatch
- made the question validation optional in the new `checkRespM`, for future zone transfer use
=> add AXFR types and error cases

.travis.yml, appveyor.yml, dns.cabal
- Require Cabal >= 2.0
- Drop GHC 8.0 support
- Test GHC 8.6.5 also on Windows
- Disable non-working doctests on Windows for now, don't know how
to link cbits/dns.c into the doctests executable.
=> Cabal and CI update

Changelog.md, Network/DNS/Utils.hs, internal/Network/DNS/Encode/Builders.hs, internal/Network/DNS/StateBinary.hs
- Change parseLabel to return Either DNSEror ... rather
than throw an exception
- Use the internal parseLabel in new splitDomain and splitMailbox
functions.
=> New splitDomain and splitMailbox functions

.github/workflows/main.yml, Network/DNS/Lookup.hs, test2/doctests.hs
Some of the underlying DNS data changed breaking doctests Also the most recent
doctests package seems to not honour some extensions in the source file.  Set
these explicity in doctests.hs.
=> Test bitrot

Network/DNS/Resolver.hs
Hi Kazu,
Haskell applications distributed as a statically linked executable typically use musl libc. This library hardcodes the `services` file location to `/etc/services` while some Linux distributions have started using GNU libc machinery (`/etc/nsswitch.conf`) to migrate `services` to `/usr/etc/services`.
While acknowledging that this is not because of a bug in the `dns` library,  using the `dns` library in the situation above would fail. 
Indeed, when resolving the address of the dns server we want to use we call `getAddrInfo` with the serivce name `domain`. This triggers a service resolution procedure provided by libc, which hits the different expectations between musl libc and gnu libc.
For consumers who need to fix this behaviour, it is useful to have a compile time flag that avoid …
=> Introduce a flag to avoid service resolution

Network/DNS/LookupRaw.hs, Network/DNS/Transport.hs
Add a new lookupRaw variant.
For example, the current time is not to be retrieved in the recv action, but passed from the outside.
=> add relaxed lookup-raw interface

internal/Network/DNS/Types/Internal.hs
The presentation form of the value for a CAA RR is the same as with DNS character strings (just not limited to 255 bytes).  Therefore, we need to use `showTXT` not `show` to present the value.
=> Use showTXT to present the value of a CAA record.
